# Generated by Django 3.1.7 on 2021-10-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20211024_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'verbose_name': 'Характеристики категорий', 'verbose_name_plural': 'Характеристики категорий'},
        ),
        migrations.AlterModelOptions(
            name='featurevalidator',
            options={'verbose_name': 'Проверка характеристик', 'verbose_name_plural': 'Проверка характеристик'},
        ),
        migrations.AlterModelOptions(
            name='productfeatures',
            options={'verbose_name': 'Характеристики продуктов', 'verbose_name_plural': 'Характеристики продуктов'},
        ),
    ]
