# Generated by Django 3.1.7 on 2021-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211024_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', editable=False, max_length=15, verbose_name='Пароль'),
        ),
    ]
