# Generated by Django 3.1.7 on 2021-05-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='movie',
            new_name='product',
        ),
    ]
