# Generated by Django 3.1.7 on 2021-05-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210507_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='text',
            new_name='comment',
        ),
    ]
