# Generated by Django 3.1.7 on 2021-05-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210507_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(max_length=5000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
