# Generated by Django 3.1.7 on 2021-05-08 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210507_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Изображение профиля'),
            preserve_default=False,
        ),
    ]
