# Generated by Django 3.1.7 on 2021-05-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210508_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='flowers/', verbose_name='Изображение'),
        ),
    ]
