# Generated by Django 3.1.7 on 2021-05-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_reviews_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='time',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='Дата комментария'),
        ),
    ]
