# Generated by Django 3.1.7 on 2021-05-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_reviews_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs/', verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.customer', verbose_name='Изображение профиля'),
        ),
    ]
