# Generated by Django 3.1.7 on 2021-05-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210511_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
