# Generated by Django 3.1.7 on 2021-05-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
    ]
