# Generated by Django 3.1.7 on 2021-05-12 06:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default=django.contrib.auth.models.User, unique=True),
        ),
    ]
