# Generated by Django 3.1.7 on 2021-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='freeship',
            field=models.BooleanField(blank=True, default=False, help_text='Если вы установите галочку - доставка бесплатная, если нет - то укажите цену доставки', null=True, verbose_name='Бесплатная доставка'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(blank=True, default=False, help_text='Если вы установите галочку - то на товар скидка, если нет - то товар без скидки', null=True, verbose_name='Акция'),
        ),
    ]
