# Generated by Django 3.1.7 on 2021-05-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20210515_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Величина скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='freeship',
            field=models.BooleanField(default=False, help_text='Если вы установите галочку - доставка бесплатная, если нет - то укажите цену доставки', verbose_name='Бесплатная доставка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, help_text='Если вы установите галочку - то на товар скидка, если нет - то товар без скидки', verbose_name='Акция'),
        ),
    ]
