# Generated by Django 3.1.7 on 2021-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210516_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Наличие товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Величина скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
