# Generated by Django 3.1.7 on 2021-05-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20210516_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='freeship',
            field=models.BooleanField(default=False, verbose_name='Бесплатная доставка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
    ]
