# Generated by Django 3.1.7 on 2021-05-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_wishes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishes',
            options={'verbose_name_plural': 'Желания'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='В процентах. Значок процента не ставить!', max_digits=9, verbose_name='Величина скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='products',
            field=models.ManyToManyField(blank=True, to='mainapp.Product', verbose_name='Товары'),
        ),
    ]
