# Generated by Django 3.1.7 on 2021-05-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20210520_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-time']},
        ),
    ]
