# Generated by Django 3.1.7 on 2021-05-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20210520_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-time'], 'verbose_name_plural': 'Отзывы'},
        ),
    ]
