# Generated by Django 3.1.7 on 2021-06-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20210520_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='slug',
        ),
    ]
