# Generated by Django 3.1.7 on 2021-06-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_remove_wishes_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishes',
        ),
    ]
