# Generated by Django 3.1.7 on 2021-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(blank=True, choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, null=True, verbose_name='Тип заказа'),
        ),
    ]
