# Generated by Django 3.1.7 on 2021-07-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_rating_ratingstar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
