# Generated by Django 3.1.7 on 2021-07-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20210702_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
