# Generated by Django 3.1.7 on 2021-07-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_auto_20210702_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_value',
            field=models.FloatField(default=0, help_text='В процентах. Значок процента не ставить!', verbose_name='Величина скидки'),
        ),
    ]
