# Generated by Django 3.1.7 on 2021-07-12 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_auto_20210703_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsToProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='Дата комментария')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('comment', models.TextField(max_length=5000, null=True, verbose_name='Комментарий')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.reviewstoproduct', verbose_name='Родитель')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-time'],
            },
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Покупатели'},
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='reviewstoproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Цветы'),
        ),
    ]
