# Generated by Django 3.1.7 on 2021-07-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20210712_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='Дата комментария')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('comment', models.TextField(max_length=5000, null=True, verbose_name='Комментарий')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.reviews', verbose_name='Родитель')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Цветы')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-time'],
            },
        ),
        migrations.DeleteModel(
            name='ReviewsToProduct',
        ),
    ]
