# Generated by Django 3.1.7 on 2021-07-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_auto_20210713_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
    ]
