# Generated by Django 3.1.7 on 2021-08-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20210713_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='freeship',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
